# Generated by Django 2.1.5 on 2019-02-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genatweetor', '0003_auto_20190118_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accountDescription',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(blank=True, upload_to='profileImages'),
        ),
    ]
