# Generated by Django 2.1.5 on 2019-03-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genatweetor', '0004_auto_20190216_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
