# Generated by Django 2.1.5 on 2019-03-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genatweetor', '0006_remove_user_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accountDescription',
            field=models.CharField(blank=True, default='hello', max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='followerCount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='tweetCount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
