# Generated by Django 2.1.5 on 2019-03-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genatweetor', '0007_auto_20190308_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweetID',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
