# Generated by Django 2.1.5 on 2019-03-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genatweetor', '0008_tweet_tweetid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twitterName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
