# Generated by Django 2.1.5 on 2019-03-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genatweetor', '0009_user_twittername'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numberOfGeneratedTweets',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='accountDescription',
            field=models.CharField(blank=True, default='Hello World! I am using Genatweetor!', max_length=300),
        ),
    ]
