# Generated by Django 2.1.5 on 2019-04-21 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genatweetor', '0012_auto_20190331_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='userTweeted',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='genatweetor.User'),
        ),
    ]
