# Generated by Django 2.1.5 on 2019-05-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genatweetor', '0014_auto_20190421_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweetFavourites',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweetRating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweetRetweets',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
