# Generated by Django 2.1.5 on 2019-05-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genatweetor', '0015_auto_20190501_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='tweetRating',
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweetScore',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
