# Generated by Django 2.1.5 on 2019-05-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genatweetor', '0019_auto_20190514_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='isGenerated',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='usedInTraining',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
