# Generated by Django 2.1.5 on 2019-05-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genatweetor', '0020_auto_20190515_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='engagementScore',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
