# Generated by Django 2.1.5 on 2019-05-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genatweetor', '0021_user_engagementscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='AverageFavouriteScore',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='user',
            name='AverageMentionScore',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='user',
            name='AverageRetweetScore',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
