# Generated by Django 2.1.5 on 2019-05-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genatweetor', '0022_auto_20190515_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='AverageMentionScore',
        ),
    ]
