# Generated by Django 2.1.5 on 2019-05-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genatweetor', '0023_remove_user_averagementionscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='AverageFavouriteScore',
        ),
        migrations.RemoveField(
            model_name='user',
            name='AverageRetweetScore',
        ),
        migrations.AlterField(
            model_name='user',
            name='engagementScore',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
