# Generated by Django 2.1.5 on 2019-05-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genatweetor', '0025_auto_20190516_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='twitterName',
        ),
    ]
