# Generated by Django 2.1.5 on 2019-05-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genatweetor', '0026_remove_user_twittername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tweetCount',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
