# Generated by Django 2.1.5 on 2019-05-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genatweetor', '0027_auto_20190516_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweetID',
            field=models.CharField(blank=True, max_length=60000, primary_key=True, serialize=False),
        ),
    ]
