# Generated by Django 2.1.5 on 2019-05-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genatweetor', '0028_auto_20190516_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweetID',
            field=models.TextField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweetText',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
